// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbbnpnsquiolmomncojd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiYm5wbnNxdWlvbG1vbW5jb2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MjI3MzksImV4cCI6MjA1MjE5ODczOX0.NyB3fx5xMlSq6d48Y7TuFK8XMHXAapF-c9MUwib5Wtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);